name: CI Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  workflow:
    name: Formatting Checks
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install packages
        run: npm ci
      - name: Check formatting
        run: npx prettier --config prettier.config.base.js --check .
